name: Deploy CloudSocial

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

steps:
- name: Deploy through SSM
  run: |
    aws ssm send-command \
      --document-name "AWS-RunShellScript" \
      --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
      --parameters '{"commands":["cd /home/ec2-user/cloudsocial","git pull origin main","sudo docker build -t cloudsocial .","sudo docker compose down","sudo docker compose up -d"]}' \
      --region "${{ secrets.AWS_REGION }}"
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
